# Generated by Django 5.0.4 on 2024-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsuarios', '0002_usuario_groups_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
